/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import Interface.AdminRole.AdminWorkAreaJPanel;
import Interface.CustomerRole.CustomerWorkAreaJPanel;
import Interface.SalesPersonRole.ManageCustomerJPanel;
import Interface.SupplierRole.SupplierWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author incha
 */
public class LoginJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Business business;
    private SupplierDirectory supplierDirectory;
    private MarketOfferCatalog marketOfferCatalog;
    private CustomerDirectory customerDirectory;
    private EmployeeDirectory employeeDirectory;

    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel() {
        initComponents();
    }

    LoginJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.supplierDirectory = business.getSupplierDirectory();
        this.marketOfferCatalog = business.getMarketOfferCatalog();
        this.customerDirectory = business.getCustomerDirectory();
        this.employeeDirectory = business.getEmployeeDirectory();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox();
        btnLogin = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jLabel4.setText("Role:");

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Supplier", "Sales Person", "Customer" }));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(btnLogin)
                            .addComponent(roleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnLogin)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        boolean login = false;
        String role = (String) roleComboBox.getSelectedItem();
        String username = usernameTextField.getText();
        String password = new String(passwordField.getPassword());
        if ((username.equals("")) || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter both the fields");
            //return;
        } else if (role.equals("Admin")) {
            if ((username.equalsIgnoreCase("Admin")) && (password.equals("Admin123"))) {
                AdminWorkAreaJPanel panel = new AdminWorkAreaJPanel(userProcessContainer, business);
                userProcessContainer.add("AdminWorkAreaJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                login = true;
            }
            if (!(login)) {
                JOptionPane.showMessageDialog(null, "Access denied!!");
            }
        } else if (role.equals("Supplier")) {
            for (Supplier supplier : business.getSupplierDirectory().getSupplierlist()) {

                if ((supplier.getUsername().equalsIgnoreCase(username)) && (supplier.getPassword().equals(password))) {
                    SupplierWorkAreaJPanel panel = new SupplierWorkAreaJPanel(userProcessContainer,business, supplier);
                    userProcessContainer.add("SupplierWorkAreaJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    login = true;
                }
            }
            if (!(login)) {
                JOptionPane.showMessageDialog(null, "Access denied!!");
            }
        } else if (role.equals(
                "Sales Person")) {
            for (Person person : business.getEmployeeDirectory().getPersonList()) {

                if ((person.getUsername().equalsIgnoreCase(username)) && (person.getPassword().equals(password))) {
                    ManageCustomerJPanel panel = new ManageCustomerJPanel(userProcessContainer, business, person);
//                    System.out.println(person);
                    userProcessContainer.add("ManageCustomerJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);

                    login = true;
                }
            }
            if (!(login)) {
                JOptionPane.showMessageDialog(null, "Access denied!!");
            }
        } else if (role.equals(
                "Customer")) {
            for (Customer customer : business.getCustomerDirectory().getCustomerList()) {

                if ((customer.getUsername().equalsIgnoreCase(username)) && (customer.getPassword().equals(password))) {
                    CustomerWorkAreaJPanel panel = new CustomerWorkAreaJPanel(userProcessContainer, business, customer);
                    userProcessContainer.add("CustomerWorkAreaJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    login = true;
                }
            }
            if (!(login)) {
                JOptionPane.showMessageDialog(null, "Access denied!!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Access denied!! USername password not recognised.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
