/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Flight;
import Business.FlightSchedule;
import Business.MasterTravelScheduler;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Airliner;
import javax.swing.JOptionPane;

/**
 *
 * @author kavyaprakash
 */
public class AddFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFlightJPanel
     */
    JPanel userProcessContainer;
    FlightSchedule flightSchedule;
    String airlinerName;
    AirlinerJPanel airliner;

    AddFlightJPanel(JPanel userProcessContainer, FlightSchedule flightSchedule, String airlinerName, AirlinerJPanel airliner) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.flightSchedule = flightSchedule;//To change body of generated methods, choose Tools | Templates.
        this.airlinerName = airlinerName;
        this.airliner = airliner;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSerialNumberAddFlight = new javax.swing.JTextField();
        txtDepartureAddFlight = new javax.swing.JTextField();
        txtDestinationAddFlight = new javax.swing.JTextField();
        txtDateAddFlight = new javax.swing.JTextField();
        txtTimeOfDayAddFlight = new javax.swing.JTextField();
        txtAvailableAddFlight = new javax.swing.JTextField();
        btnSubmitAddFlight = new javax.swing.JButton();
        btnBackAddFlight = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("ADD FLIGHT");

        jLabel2.setText("Serial Number:");

        jLabel3.setText("Departure:");

        jLabel4.setText("Destination:");

        jLabel5.setText("Date:");

        jLabel6.setText("Time of day:");

        jLabel7.setText("Available:");

        btnSubmitAddFlight.setText("SUBMIT");
        btnSubmitAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAddFlightActionPerformed(evt);
            }
        });

        btnBackAddFlight.setText("<<BACK");
        btnBackAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAddFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDepartureAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestinationAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimeOfDayAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAvailableAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNumberAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnSubmitAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBackAddFlight)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNumberAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDepartureAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDestinationAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDateAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTimeOfDayAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAvailableAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAddFlightActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        airliner.populateFlightsTable(airlinerName);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackAddFlightActionPerformed

    private void btnSubmitAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAddFlightActionPerformed
        // TODO add your handling code here:

        if (isInvalid(txtDepartureAddFlight.getText())) {
            JOptionPane.showMessageDialog(null, "Departure cannot be empty or number");
            return;
        }

        if (isInvalid(txtDestinationAddFlight.getText())) {
            JOptionPane.showMessageDialog(null, "Destination cannot be empty or number");
            return;
        }
        if(isInvalid(txtTimeOfDayAddFlight.getText())){
           JOptionPane.showMessageDialog(null, "Time of day cannot be empty or number");
            return; 
        } 
        
         if (txtDateAddFlight.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Date cannot be empty");
            return;
        }


        Flight flight = new Flight();
        flight.setDeparture(txtDepartureAddFlight.getText());
        flight.setDate(txtDateAddFlight.getText());
        flight.setDestination(txtDestinationAddFlight.getText());
        try {
            Integer.parseInt(txtSerialNumberAddFlight.getText());
            flight.setSerialNumber(txtSerialNumberAddFlight.getText());
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(null, "Serial number needs to be a number");
            return;

        }
        flight.setTimeOfDay(txtTimeOfDayAddFlight.getText());
        if (airlinerName.equalsIgnoreCase("AirIndia")) {
            flightSchedule.getFlightListAirIndia().add(flight);
        } else if (airlinerName.equalsIgnoreCase("Luftansa")) {

            flightSchedule.getFlightListLuftansa().add(flight);

        }
        JOptionPane.showMessageDialog(null, "Flight added successfully");

    }//GEN-LAST:event_btnSubmitAddFlightActionPerformed
    public boolean isInvalid(String input) {
        if (input.isEmpty()) {
            return true;
        }
        try {
            Double.parseDouble(input);
        } catch (NullPointerException ne) {
            return false;
        } catch (NumberFormatException ne) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackAddFlight;
    private javax.swing.JButton btnSubmitAddFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAvailableAddFlight;
    private javax.swing.JTextField txtDateAddFlight;
    private javax.swing.JTextField txtDepartureAddFlight;
    private javax.swing.JTextField txtDestinationAddFlight;
    private javax.swing.JTextField txtSerialNumberAddFlight;
    private javax.swing.JTextField txtTimeOfDayAddFlight;
    // End of variables declaration//GEN-END:variables
}
