/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.MasterTravelScheduler;
import Business.Airliner;
import Business.FlightSchedule;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kavyaprakash
 */
public class TravelAgentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelAgentJPanel
     */
    JPanel userProcessContainer;
    MasterTravelScheduler masterTravelScheduler;
    FlightSchedule flightSchedule;

    public TravelAgentJPanel(JPanel userProcessContainer, MasterTravelScheduler masterTravelScheduler) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.masterTravelScheduler = masterTravelScheduler;
        
        populateAirlinersTable();

        
    }
    
    public void populateAirlinersTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblTAAirliners.getModel();
        dtm.setRowCount(0);

        for (Airliner ar : this.masterTravelScheduler.getMasterTravelList()) {
            Object row[] = new Object[1];
            row[0] = ar;
            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTAAirliners = new javax.swing.JTable();
        btnBrowseAirliner = new javax.swing.JButton();
        btnDeleteAirliner = new javax.swing.JButton();
        btnAddAirliner1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Travel Agent");

        tblTAAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AirlinerName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTAAirliners);
        if (tblTAAirliners.getColumnModel().getColumnCount() > 0) {
            tblTAAirliners.getColumnModel().getColumn(0).setResizable(false);
        }

        btnBrowseAirliner.setText("BROWSE FLIGHTS");
        btnBrowseAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseAirlinerActionPerformed(evt);
            }
        });

        btnDeleteAirliner.setText("DELETE AIRLINER");
        btnDeleteAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirlinerActionPerformed(evt);
            }
        });

        btnAddAirliner1.setText("ADD AIRLINER");
        btnAddAirliner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirliner1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBrowseAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAddAirliner1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)
                                .addComponent(btnDeleteAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAirliner1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnBrowseAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirlinerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTAAirliners.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            Airliner ar = (Airliner)tblTAAirliners.getValueAt(selectedRow,0); 
            masterTravelScheduler.deleteAirliner(ar);
            JOptionPane.showMessageDialog(null," Airliner has been deleted");
            populateAirlinersTable();
    }//GEN-LAST:event_btnDeleteAirlinerActionPerformed
    }
    private void btnAddAirliner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirliner1ActionPerformed
        // TODO add your handling code here:
        AddAirlinerJPanel panel = new AddAirlinerJPanel(userProcessContainer, masterTravelScheduler,this);
        userProcessContainer.add("AddAirlinerJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddAirliner1ActionPerformed

    private void btnBrowseAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseAirlinerActionPerformed
        // TODO add your handling code here:
        Airliner airliner1=(Airliner)tblTAAirliners.getValueAt(tblTAAirliners.getSelectedRow(),0);
        BrowseFlightsTAJPanel panel = new BrowseFlightsTAJPanel(userProcessContainer,masterTravelScheduler,airliner1);
        userProcessContainer.add("AddAirlinerJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBrowseAirlinerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirliner1;
    private javax.swing.JButton btnBrowseAirliner;
    private javax.swing.JButton btnDeleteAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTAAirliners;
    // End of variables declaration//GEN-END:variables
}
