/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Account;
import Business.AccountDirectory;
import Business.Person;
import Business.PersonDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kavyaprakash
 */
public class FindPersonJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
 PersonDirectory personDirectory;
 //ManagePersonDirectoryJPanel managepersonJPanel;
 Person personFound;
 AccountDirectory userAccountDirectory;
    /**
     * Creates new form FindPersonJPanel
     */
    public FindPersonJPanel(JPanel userProcessContainer, Person personFound,AccountDirectory userAccountDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        //this.managepersonJPanel = managepersonJPanel;
        this.personFound = personFound;
        this.userAccountDirectory = userAccountDirectory;
        
        txtFirstNameFP.setText(personFound.getFirstName());
        txtLastNameFP.setText(personFound.getLastName());
        txtFirstNameFP.setEditable(false);
        txtLastNameFP.setEditable(false);
        
        //Populate the usernames table for the particular person
        
        for(Account a : userAccountDirectory.getAccountList()){
            if(a.getPerson().equals(personFound))
            {
                DefaultTableModel dtm = (DefaultTableModel) tblFindPersonTable.getModel();
                Object[] row = new Object[2];
                row[0] = a.getUserName();
                row[1] = a.getRole();
                dtm.addRow(row);
    
            }
            
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFindPersonTable = new javax.swing.JTable();
        txtFirstNameFP = new javax.swing.JTextField();
        txtLastNameFP = new javax.swing.JTextField();
        btnBackFP = new javax.swing.JButton();

        jLabel1.setText("FirstName:");

        jLabel4.setText("LastName:");

        jLabel6.setText("UserNames:");

        jLabel7.setText("Find Person Details");

        tblFindPersonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "userNames", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFindPersonTable);
        if (tblFindPersonTable.getColumnModel().getColumnCount() > 0) {
            tblFindPersonTable.getColumnModel().getColumn(0).setResizable(false);
            tblFindPersonTable.getColumnModel().getColumn(1).setResizable(false);
        }

        btnBackFP.setText("<<BACK");
        btnBackFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(txtFirstNameFP, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(txtLastNameFP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnBackFP)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel7)))
                .addGap(286, 286, 286))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnBackFP))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstNameFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastNameFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFPActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        //managepersonJPanel.populatePersonTable();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackFPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackFP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFindPersonTable;
    private javax.swing.JTextField txtFirstNameFP;
    private javax.swing.JTextField txtLastNameFP;
    // End of variables declaration//GEN-END:variables
}
