/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Account;
import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author kavyaprakash
 */
public class UpdateUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateUserAccountJPanel
     */
    JPanel userProcessContainer;
    AccountDirectory userAccountDirectory;
    ManageUserAccountsJPanel manageUserAccountsJPanel;
    Account accountSelected;
    
    UpdateUserAccountJPanel(JPanel userProcessContainer, AccountDirectory userAccountDirectory,Account accountSelected,ManageUserAccountsJPanel manageUserAccountsJPanel) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        
        this.userProcessContainer = userProcessContainer;
        this.userAccountDirectory = userAccountDirectory;
        this.manageUserAccountsJPanel = manageUserAccountsJPanel;
        this.accountSelected = accountSelected;
        
       radioBtnActive.setActionCommand("Active");
       radioBtnInactive.setActionCommand("Inactive");
        
        for (Account a : userAccountDirectory.getAccountList()) {
            comboBoxRoleUpdateUserAccount.addItem(a.getRole());
        }
        
        txtPersonUpdateUserAccount.setText(accountSelected.getPerson().toString());
        txtPersonUpdateUserAccount.setEditable(false);
        txtPasswordUpdateUserAccount.setText(accountSelected.getPassword());
        txtUserNameUpdateUserAccount.setText(accountSelected.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPersonUpdateUserAccount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUserNameUpdateUserAccount = new javax.swing.JTextField();
        txtPasswordUpdateUserAccount = new javax.swing.JTextField();
        comboBoxRoleUpdateUserAccount = new javax.swing.JComboBox();
        btnUpdateUserAccount = new javax.swing.JButton();
        btnCancelUpdateUserAccount = new javax.swing.JButton();
        radioBtnInactive = new javax.swing.JRadioButton();
        radioBtnActive = new javax.swing.JRadioButton();
        btnBackUUA = new javax.swing.JButton();

        jLabel1.setText("UPDATE USER ACCOUNT");

        jLabel3.setText("Person:");

        jLabel4.setText("Role:");

        jLabel2.setText("Username:");

        txtPersonUpdateUserAccount.setEditable(false);
        txtPersonUpdateUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonUpdateUserAccountActionPerformed(evt);
            }
        });

        jLabel5.setText("Password:");

        btnUpdateUserAccount.setText("UPDATE");
        btnUpdateUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserAccountActionPerformed(evt);
            }
        });

        btnCancelUpdateUserAccount.setText("CANCEL");

        buttonGroup1.add(radioBtnInactive);
        radioBtnInactive.setText("Inactive");
        radioBtnInactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnInactiveActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnActive);
        radioBtnActive.setText("Active");
        radioBtnActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnActiveActionPerformed(evt);
            }
        });

        btnBackUUA.setText("<<BACK");
        btnBackUUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUUAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBackUUA)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnUpdateUserAccount)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelUpdateUserAccount)))
                .addGap(0, 214, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPasswordUpdateUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserNameUpdateUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtPersonUpdateUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxRoleUpdateUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBtnActive)
                            .addComponent(radioBtnInactive))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackUUA)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPersonUpdateUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboBoxRoleUpdateUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUserNameUpdateUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPasswordUpdateUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateUserAccount)
                            .addComponent(btnCancelUpdateUserAccount)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(radioBtnActive)
                        .addGap(18, 18, 18)
                        .addComponent(radioBtnInactive)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonUpdateUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonUpdateUserAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonUpdateUserAccountActionPerformed

    private void btnBackUUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUUAActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        manageUserAccountsJPanel.populateAccountsTable();
    }//GEN-LAST:event_btnBackUUAActionPerformed

    private void btnUpdateUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserAccountActionPerformed
        // TODO add your handling code here:
       accountSelected.setUserName(txtUserNameUpdateUserAccount.getText());
       accountSelected.setPassword(txtPasswordUpdateUserAccount.getText());
       accountSelected.setRole((String)comboBoxRoleUpdateUserAccount.getSelectedItem());
       String selected = buttonGroup1.getSelection().getActionCommand();
       //statusInput.addActionListener(accountSelected.setStatus());
       if(selected.equalsIgnoreCase("Active")){
           accountSelected.setStatus("Active");
       }
       
       if(selected.equalsIgnoreCase("Inactive")){
           accountSelected.setStatus("Inactive");
       }
     
       
       JOptionPane.showMessageDialog(null,"Account updated successfully");
       manageUserAccountsJPanel.populateAccountsTable();
    }//GEN-LAST:event_btnUpdateUserAccountActionPerformed

    private void radioBtnActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnActiveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_radioBtnActiveActionPerformed

    private void radioBtnInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnInactiveActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_radioBtnInactiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackUUA;
    private javax.swing.JButton btnCancelUpdateUserAccount;
    private javax.swing.JButton btnUpdateUserAccount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox comboBoxRoleUpdateUserAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radioBtnActive;
    private javax.swing.JRadioButton radioBtnInactive;
    private javax.swing.JTextField txtPasswordUpdateUserAccount;
    private javax.swing.JTextField txtPersonUpdateUserAccount;
    private javax.swing.JTextField txtUserNameUpdateUserAccount;
    // End of variables declaration//GEN-END:variables
}
